#!/usr/bin/env bash
# This bash script displays list of current running proc

# shellcheck disable=all

PID=$(top | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')

echo kill "$PID"