#!/usr/bin/env bash
# This bash script displays list of current running proc

# shellcheck disable=SC2009

PID=$(ps aux | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')


kill "$PID"