#!/usr/bin/env bash
# This script is displaying "Best School" till the 9th iteration

count=0

while [ "$count" -lt 10 ]
do
    if [ "$count" == 9 ]; then echo "Hi" ; fi
    echo "Best School"
    count=$((count + 1))
done
