#!/usr/bin/env bash
# This script is displaying "Best School". 4th itr prints bad 8th itr prints good luck

count=0

while [ "$count" -lt 10 ]
do
    if [ "$count" == 4 ]
    then
         echo "bad luck" ;
    elif [ "$count" == 8 ]; 
    then 
        echo "good luck" ; 
    else
        echo "Best School"
    fi
    count=$((count + 1))
done

