#!/usr/bin/env bash
# Scripts checks to see if a file exist

if [ -e "school" ]; then  # Check if file exists
  echo "school file exists"
  if [ -s "school" ]; then  # Check if file is not empty
    echo "school file is not empty"
    if [ -f "school" ]; then  # Check if file is a regular file
      echo "school is a regular file"
    fi
  else
    echo "school file is empty"
  fi
else
  echo "school file does not exist"
fi

